/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.Usuario;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import modelo.Prestamo;
import modelo.Recurso;

/**
 *
 * @author jhon
 */
public class AdministrarPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarUsuarios
     */
    public AdministrarPrestamos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vacio = true;
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtIDrecurso = new javax.swing.JTextField();
        txtIDusuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        estadoPrestamo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        mesReg = new JComboBox<>();
        anioReg = new JComboBox<>();
        diaReg = new JComboBox<>();

        mesDev = new JComboBox<>();
        anioDev = new JComboBox<>();
        diaDev = new JComboBox<>();

        mesLim = new JComboBox<>();
        anioLim = new JComboBox<>();
        diaLim = new JComboBox<>();

        


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("ID Préstamo :");

        jLabel2.setText("ID Recurso :");

        jLabel3.setText("ID Usuario :");

        jLabel4.setText("Estado :");

        jLabel5.setText("Fecha Registro :");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        okBtn.setText("Ok");

        btnEliminar.setText("Eliminar");

        estadoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Abierto", "Parcialmente Cerrado", "Completamente Cerrado" }));
        estadoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoPrestamoActionPerformed(evt);
            }
        });

        // Populate the dayComboBox with days from 1 to maxDays

        diaReg.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        mesReg.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        anioReg.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));

        diaDev.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        mesDev.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        anioDev.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));

        diaLim.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        mesLim.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        anioLim.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));
        for (int i = 0; i < 12; i++) {
            mesReg.addItem(i + 1);
            mesDev.addItem(i + 1);
            mesLim.addItem(i + 1);
        }

        for (int i = 0; i < 31; i++) {
            diaReg.addItem(i + 1);
            diaDev.addItem(i + 1);
            diaLim.addItem(i + 1);
        }

        int anioActual = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = anioActual - 10; i <= anioActual + 10; i++) {
            anioReg.addItem(i);
            anioDev.addItem(i);
            anioLim.addItem(i);
        }

        jLabel6.setText("Fecha Límite :");

        jLabel7.setText("Fecha Devolución :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(diaDev)
                                                .addComponent(mesDev)
                                                .addComponent(anioDev)
                                                .addGap(249, 249, 249))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel2))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtID,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                103,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtIDusuario,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                103,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtIDrecurso,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                103,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(estadoPrestamo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                103,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(btnGuardar,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btnListar,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(btnEditar,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        87,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(okBtn,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        49, Short.MAX_VALUE))
                                                                        .addComponent(btnEliminar,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))))))

                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(diaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(mesReg, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(anioReg, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))

                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(diaLim, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(mesLim, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(anioLim, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))

        );

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnListar)
                                        .addComponent(txtIDusuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnEditar)
                                        .addComponent(okBtn)
                                        .addComponent(jLabel2)
                                        .addComponent(txtIDrecurso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(btnEliminar))
                                        .addComponent(estadoPrestamo, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diaReg, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesReg, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anioReg, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6))

                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diaLim, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesLim, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anioLim, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(diaDev, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesDev, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anioDev, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[] {
                        "ID", "Usuario", "Recurso", "Estado", "F. Registro", "F. Limite", "Fecha Devolución"
                }));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabla() {
        return jTable1;
    }

    public int getID() {
        return Integer.parseInt(txtID.getText());
    }

    public void addComboBoxListener(ActionListener listenControles) {
        estadoPrestamo.addActionListener(listenControles);
    }

    public void setDatos(int ID, int IDusuario, int IDrecurso, 
    int diaFechar, int mesFechar, int anioFechar, 
    int diaFechal, int mesFechal, int anioFechal,
    int diaFechad, int mesFechad, int anioFechad) {
        setID(ID);
        setIDUsuario(IDusuario);
        setIDRecurso(IDrecurso);
        setFechaReg(diaFechar, mesFechar, anioFechar);
        setFechaLim(diaFechal, mesFechal, anioFechal);
        setFechaDev(diaFechad, mesFechad, anioFechad);
    }

    public void addRegistroListener(ActionListener listenControles) {
        diaReg.addActionListener(listenControles);
        mesReg.addActionListener(listenControles);
        anioReg.addActionListener(listenControles);
    }

    public void addLimiteListener(ActionListener listenControles) {
        diaLim.addActionListener(listenControles);
        mesLim.addActionListener(listenControles);
        anioLim.addActionListener(listenControles);
    }

    public void addDevolucionListener(ActionListener listenControles) {
        diaDev.addActionListener(listenControles);
        mesDev.addActionListener(listenControles);
        anioDev.addActionListener(listenControles);
    }


    public JComboBox<String> getComboBox() {
        return estadoPrestamo;
    }

    public int getIDRecurso() {
        return Integer.parseInt(txtIDrecurso.getText());
    }

    public int getIDUsuario() {
        return Integer.parseInt(txtIDusuario.getText());
    }

 

    public String getDiaDev() {
        return diaDev.getSelectedItem().toString();
    }

    public String getMesDev() {
        return mesDev.getSelectedItem().toString();
    }
    public String getAnioDev() {
        return anioDev.getSelectedItem().toString();
    }


    public String getDiaLim() {
        return diaLim.getSelectedItem().toString();
    }

    public String getMesLim() {
        return mesLim.getSelectedItem().toString();
    }
    public String getAnioLim() {
        return anioLim.getSelectedItem().toString();
    }

    public String getDiaReg() {
        return diaReg.getSelectedItem().toString();
    }

    public String getMesReg() {
        return mesReg.getSelectedItem().toString();
    }
    public String getAnioReg() {
        return anioReg.getSelectedItem().toString();
    }

    public void setDiaDev(int index) {
        diaDev.setSelectedIndex(index-1);
    }

    public void setMesDev(int index) {
        mesDev.setSelectedIndex(index-1);
    }

    public void setAnioDev(int index) {
        anioDev.setSelectedIndex(index-1);
    }

    public void setFechaDev(int indexDia, int indexMes, int indexAnio) {
        diaDev.setSelectedIndex(indexDia-1);
        mesDev.setSelectedIndex(indexMes-1);
        anioDev.setSelectedItem(indexAnio);
    }

    public void setDiaReg(int index) {
        diaReg.setSelectedIndex(index-1);
    }

    public void setMesReg(int index) {
        mesReg.setSelectedIndex(index-1);
    }

    public void setAnioReg(int index) {
        anioReg.setSelectedIndex(index-1);
    }

    public void setFechaReg(int indexDia, int indexMes, int indexAnio) {
        diaReg.setSelectedIndex(indexDia-1);
        mesReg.setSelectedIndex(indexMes-1);
        anioReg.setSelectedItem(indexAnio);
    }


    public void setDiaLim(int index) {
        diaLim.setSelectedIndex(index-1);
    }

    public void setMesLim(int index) {
        mesLim.setSelectedIndex(index-1);
    }

    public void setAnioLim(int index) {
        anioLim.setSelectedIndex(index-1);
    }

    public void setFechaLim(int indexDia, int indexMes, int indexAnio) {
        diaLim.setSelectedIndex(indexDia-1);
        mesLim.setSelectedIndex(indexMes-1);
        anioLim.setSelectedItem(indexAnio);
    }


    public void setID(int ID) {
        txtID.setText(String.valueOf(ID));
        
    }


    public void setIDRecurso(int idrecurso) {
        txtIDrecurso.setText(String.valueOf(idrecurso));
        
    }

    public void setIDUsuario(int idusuario) {
        txtIDusuario.setText(String.valueOf(idusuario));
        
    }

    public boolean getEstaVacio(){
        return vacio;
    }

    public void setIDVacio() {
        txtID.setText("");
        txtIDrecurso.setText("");
        txtIDusuario.setText("");
        vacio = false;
    }

    public void setCamposVacios() {
        setIDVacio();
        //setFechaL("");
        // setFechaD("");
    }

    public void displayErrorMessage(String erroMessage) {
        JOptionPane.showMessageDialog(this, erroMessage);
    }

    public void btnGuardarListener(ActionListener listenControles) {
        btnGuardar.addActionListener(listenControles);
    }

    public void btnListarListener(ActionListener listenControles) {
        btnListar.addActionListener(listenControles);
    }

    public void btnEditarListener(ActionListener listenControles) {
        btnEditar.addActionListener(listenControles);
    }

    public void btnEliminarListener(ActionListener listenControles) {
        btnEliminar.addActionListener(listenControles);
    }

    public void btnOkListener(ActionListener listenControles) {
        okBtn.addActionListener(listenControles);
    }

    

    public void jTableListener(MouseAdapter listenControles) {
        jTable1.addMouseListener(listenControles);
    }

    public Object[] getDatosPrestamo(Prestamo prestamo) {
        Object[] elemento = { prestamo.getID(), prestamo.getIDusuario(), prestamo.getIDrecurso(), prestamo.getEstado(),
                prestamo.getFechaRegistro(), prestamo.getFechaLimite(), prestamo.getFechaDevolucion() };
        return elemento;
    }


    


    public void setComboBox(int index) {
        estadoPrestamo.setSelectedIndex(index);
    }

    public Object[][] getDatosTabla() {
        return data;
    }

    public void addDatosTabla(Prestamo prestamo) {
        // Crear una nueva matriz temporal con una fila adicional
        Object[][] newData = new Object[data.length + 1][];

        // Copiar los elementos existentes de data a newData
        for (int i = 0; i < data.length; i++) {
            newData[i] = data[i];
        }

        // Añadir el nuevo elemento a newData
        newData[newData.length - 1] = getDatosPrestamo(prestamo);

        // Asignar newData a data
        data = newData;

        // Copiar los elementos existentes de data a newData
        // swingutilites para envolver el código de actualización de la interfaz de
        // usuario.
        SwingUtilities.invokeLater(() -> {
            jTable1.setModel(getModeloTabla());
        });

        System.out.println(jTable1.getModel());

    }

    public void editarElementoTabla(int Index, Prestamo prestamo) {
        Object[] nuevosDatos = getDatosPrestamo(prestamo);
        data[Index] = nuevosDatos;
        SwingUtilities.invokeLater(() -> {
            jTable1.setModel(getModeloTabla());
        });
    }

    public void eliminarFila(int filaEliminar) {

        // Convertir la matriz en una lista de arreglos
        List<Object[]> listaMatriz = new ArrayList<>(Arrays.asList(data));

        // Eliminar la fila especificada
        listaMatriz.remove(filaEliminar);

        // Convertir la lista de arreglos nuevamente en una matriz
        Object[][] nuevaMatriz = new Object[listaMatriz.size()][];
        listaMatriz.toArray(nuevaMatriz);

        data = nuevaMatriz;

        SwingUtilities.invokeLater(() -> {
            jTable1.setModel(getModeloTabla());
        });
    }

    public DefaultTableModel getModeloTabla() {
        DefaultTableModel modeloTabla = new DefaultTableModel(
                data,
                new String[] {
                        "ID", "Usuario", "Recurso", "Estado", "F. Registro", "F. Límite", "F. Devolución"
                });
        return modeloTabla;
    }

    public void deshabilitarGuardar() {
        btnGuardar.setEnabled(false);
    }

    public void habilitarGuardar() {
        btnGuardar.setEnabled(true);
    }

    public void habilitarEditar(boolean toggle) {
        if (toggle == true) {
            btnEditar.setEnabled(true);
        } else {
            btnEditar.setEnabled(false);
        }
    }

    public void habilitarEliminar(boolean toggle) {
        if (toggle == true) {
            btnEliminar.setEnabled(true);
        } else {
            btnEliminar.setEnabled(false);
        }
    }

    /**
     */
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnListarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEditarActionPerformed

    private void estadoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estadoPrestamoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_estadoPrestamoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarPrestamos().setVisible(true);
            }
        });
    }

    boolean vacio; // verifica si todo está vacio
    private DefaultTableModel model;
    private Object[][] data = {};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> estadoPrestamo;
    private javax.swing.JComboBox<Integer> diaReg;
    private javax.swing.JComboBox<Integer> mesReg;
    private javax.swing.JComboBox<Integer> anioReg;
    private javax.swing.JComboBox<Integer> diaLim;
    private javax.swing.JComboBox<Integer> mesLim;
    private javax.swing.JComboBox<Integer> anioLim;
    private javax.swing.JComboBox<Integer> diaDev;
    private javax.swing.JComboBox<Integer> mesDev;
    private javax.swing.JComboBox<Integer> anioDev;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDrecurso;
    private javax.swing.JTextField txtIDusuario;
    // End of variables declaration//GEN-END:variables

}
